services:
  lms-edge-gateway:
    build:
      context: ./lms_edge_gateway
      args:
        BUILD_FROM: ghcr.io/home-assistant/amd64-base:latest
        BUILD_ARCH: amd64
        BUILD_VERSION: 0.1.9
    ports:
      - "5000:5000"
      - "18080:18080"
    volumes:
      - ./local-data:/data
    environment:
      ASPNETCORE_ENVIRONMENT: Production
