const assert=require('node:assert/strict');
const b=require('../src/HA.LMS.EnergyStudio/wwwroot/ha-bindings.js');
const e=(state,unit,attributes={})=>({entity_id:'sensor.example',state,last_updated:new Date().toISOString(),attributes:{unit_of_measurement:unit,...attributes}});
assert.equal(b.read({entityId:'sensor.example'},e('3400','W'),'power').value,3.4);
assert.equal(b.read({entityId:'sensor.example',invert:true},e('-3400','W'),'power').value,3.4);
assert.equal(b.read({entityId:'sensor.example'},e('12500','Wh'),'energy').value,12.5);
assert.equal(b.read({entityId:'sensor.example'},e('100','kWh'),'power').quality,'unit-mismatch');
assert.equal(b.read({entityId:'sensor.example'},e('unavailable','W'),'power').value,null);
assert.equal(b.read({entityId:'sensor.example'},e('','W'),'power').value,null);
assert.equal(b.read({entityId:'sensor.example'},e('Infinity','W'),'power').value,null);
assert.equal(b.read({entityId:'sensor.example'},e('101','%'),'soc').quality,'out-of-range');
assert.equal(b.read({entityId:'sensor.example'},e('77','°F'),'temperature').value,25);
assert.equal(b.read({entityId:'sensor.example'},e('on',null),'boolean').value,true);
assert.equal(b.read({entityId:'sensor.example'},e('nonsense',null),'boolean').value,null);
const array=e('online',undefined,{cells:[{voltage:3.32,current:-800,balancing:true}]});
assert.equal(b.read({entityId:'sensor.example',pointer:'/attributes/cells/0/voltage',sourceUnit:'V'},array,'voltage').value,3.32);
assert.equal(b.read({entityId:'sensor.example',pointer:'/attributes/cells/0/current',sourceUnit:'mA'},array,'current').value,-.8);
assert.equal(b.read({entityId:'sensor.example',pointer:'/attributes/cells/0/balancing'},array,'boolean').value,true);
assert.equal(b.read({entityId:'sensor.example',pointer:'/attributes/missing',sourceUnit:'V'},array,'voltage').value,null);
assert.equal(b.pointer(array,'/__proto__/polluted'),undefined);
assert.equal(b.read({entityId:'sensor.example',pointer:'attributes/cells',sourceUnit:'V'},array,'voltage').quality,'invalid-pointer');
assert.equal(b.read({entityId:'sensor.example',maxAgeSeconds:1},{...e('1','W'),last_updated:'2000-01-01T00:00:00Z'},'power').quality,'stale');
assert.equal(b.read({entityId:'sensor.example'},e('0','W'),'power').value,0);
assert.equal(b.net({value:4,quality:'good'},{value:6,quality:'good'}).value,-2);
assert.equal(b.net({value:4,quality:'good'},{value:null,quality:'unavailable'}).value,null);
assert.equal(b.candidates([e('2','W'),e('3','kWh')],'power').length,1);
assert.equal(b.candidates([array],'voltage','', '',true).length,1);
const fields=b.fields({loads:[{id:'heat',name:'Heat pump'}],storage:[{id:'dc',name:'DC bank'}],vehicles:[],cars:0},{dc:['cell-1']});
assert(fields.some(f=>f.key==='loads.heat'&&f.role==='power'));
assert(fields.some(f=>f.key==='cells.dc.cell-1.voltage'));
assert.equal(b.evaluate({},[],fields)['loads.heat'].quality,'unmapped');
console.log('PASS: units, signs, null quality, BMS attribute arrays, availability, freshness, paired flows and picker filters.');
